language: python

python:
  - "2.7"

install_script: pip install -r requirements.txt

# Dummy command until we have real tests
script: true

branches:
  only:
    - master

deploy:
  provider: heroku
  # Required for some reason (default anvil strategy doesn't work)
  # See: https://botbot.me/freenode/gittip/msg/13686229/
  strategy: git
  api_key:
    secure: DEgQdY5qAukGtKb2kBh00g9iY5+ncKcIxT59H0Yart/1qW56IrrDdZnm4Cb8mx6yIw+Jn2W6wKnLTXl0tDivO+tzv981uk3Wa49bmU7sF9XxaO35BhspvfmPQIUodjsjVe3gUs2OVbPZJaJn/z0k1nClQmJGmzNVYIAvfD07VUQ=
  app:
    master: building-gittip-com
  on:
    repo: gittip/building.gittip.com
    branch: master

before_deploy:
  - cd www/repos
  - git clone https://github.com/gittip/www.gittip.com.git
  - git clone https://github.com/gittip/gttp.co.git
  - git clone https://github.com/gittip/Gittip-Everywhere.git

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.org#gittip"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
