language: python

python:
  - "2.7"

install:
  - make env

before_script:
  - make run&
  - sleep 3  # Give webserver some time to start

# Dummy command until we have real tests
script:
  - curl http://localhost:8536/

branches:
  only:
    - master

deploy:
  provider: heroku
  # Required for some reason (default anvil strategy doesn't work)
  # See: https://botbot.me/freenode/gittip/msg/13686229/
  strategy: git
  api_key:
    secure: "PlaeO2woN4LUCtCg2GjOzbXkp9OGR0UHKmsge6RLcCjLBisNWX3akxLDh8zyqNm4BKRmG1sTNw0GHssSniCYf0RtF5PwVeP4K5DRPMVcLtcfOxbVEsU4Bq8/5MKqArPC2mG9qiG8/4gtkE4XtAUbdjU0MWpfLT2pmmpp8kuDd7k="
  app:
    master: inside-gratipay-com
  on:
    repo: gratipay/inside.gratipay.com
    branch: master

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.org#gratipay"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

sudo: false
